import type { Metadata } from "next";
import { DM_Serif_Text, Sora } from "next/font/google";
import "./globals.css";

const dmSerifText = DM_Serif_Text({
  subsets: ["latin"],
  weight: "400", // DM Serif Text has only one weight
  variable: "--font-dm-serif-text",
});

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSerifText.variable} ${sora.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}